### ISSUE TITLE
Fails on launch on linux

### ISSUE THREAD

**Issue by luigino** [jonata/opendvdproducer#27]
```
~> opendvdproducer 
/usr/share/opendvdproducer/graphics
Traceback (most recent call last):
  File "/usr/share/opendvdproducer/opendvdproducer.py", line 3988, in <module>
    app.main = main_window()
  File "/usr/share/opendvdproducer/opendvdproducer.py", line 1090, in __init__
    self.preview_video_obj.set_xwindow(self.preview_video_widget.winId())
AttributeError: 'main_window' object has no attribute 'preview_video_obj'
```

I have python-pyside installed, am I doing something wrong?

**Comment by jonata** [comment]
Hi all

I am moving the development to GitLab and hopefully will update the software. See you there!
https://gitlab.com/jonata/opendvdproducer

Thanks for your attention.
